// Rendering half of the translator: the generated godip variant package.
package main

import (
	"fmt"
	"go/format"
	"log"
	"sort"
	"strings"
)

// goIdent turns a power name into a Go identifier: "Sail Ho!" style names
// and multi-word powers both survive.
func goIdent(name string) string {
	out := strings.Builder{}
	upper := true
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9':
			if upper {
				out.WriteString(strings.ToUpper(string(r)))
				upper = false
			} else {
				out.WriteRune(r)
			}
		default:
			upper = true
		}
	}
	ident := out.String()
	if ident == "" || (ident[0] >= '0' && ident[0] <= '9') {
		ident = "P" + ident
	}
	return ident
}

// quote renders a Go string literal.
func quote(s string) string {
	return fmt.Sprintf("%q", s)
}

// backquote renders a raw Go string literal, falling back to a quoted one
// when the text contains a backquote.
func backquote(s string) string {
	if strings.Contains(s, "`") {
		return quote(s)
	}
	return "`" + s + "`"
}

// flagsFor renders the godip flag arguments for a province.
func flagsFor(p *province) string {
	switch {
	case p.convoyable:
		return "godip.Archipelago..."
	case len(p.land) > 0 && len(p.sea) > 0:
		return "godip.Coast..."
	case len(p.sea) > 0:
		return "godip.Sea"
	default:
		return "godip.Land"
	}
}

// edgeFlag is the flag one edge carries: army edges are Land, everything a
// fleet uses is Sea.
func edgeFlag(kind string) string {
	if kind == "land" {
		return "godip.Land"
	}
	return "godip.Sea"
}

// renderGraph writes the graph builder chain, one line per province.
func renderGraph(m *model) string {
	out := strings.Builder{}
	for _, key := range m.order {
		p := m.provinces[key]

		// An edge that both an army and a fleet may use is declared once
		// with both flags, exactly as godip's own variants do.
		land := map[string]bool{}
		for _, ref := range p.land {
			land[godipRef(ref)] = true
		}
		sea := map[string]bool{}
		for _, ref := range p.sea {
			sea[godipRef(ref)] = true
		}
		targets := []string{}
		for ref := range land {
			targets = append(targets, ref)
		}
		for ref := range sea {
			if !land[ref] {
				targets = append(targets, ref)
			}
		}
		sort.Strings(targets)

		out.WriteString("\t\t// " + p.name + "\n")
		out.WriteString("\t\tProv(" + quote(key) + ")")
		for _, ref := range targets {
			switch {
			case land[ref] && sea[ref]:
				out.WriteString(".Conn(" + quote(ref) + ", godip.Coast...)")
			case land[ref]:
				out.WriteString(".Conn(" + quote(ref) + ", " + edgeFlag("land") + ")")
			default:
				out.WriteString(".Conn(" + quote(ref) + ", " + edgeFlag("sea") + ")")
			}
		}
		out.WriteString(".Flag(" + flagsFor(p) + ")")
		out.WriteString(renderSC(m, key))
		out.WriteString(".\n")

		// Named coasts are their own sea-only provinces.
		codes := []string{}
		for code := range p.coasts {
			codes = append(codes, code)
		}
		sort.Strings(codes)
		for _, code := range codes {
			refs := map[string]bool{}
			for _, ref := range p.coasts[code] {
				refs[godipRef(ref)] = true
			}
			list := []string{}
			for ref := range refs {
				list = append(list, ref)
			}
			sort.Strings(list)
			out.WriteString("\t\t// " + p.name + " (" + code + ")\n")
			out.WriteString("\t\tProv(" + quote(key+"/"+code) + ")")
			for _, ref := range list {
				out.WriteString(".Conn(" + quote(ref) + ", godip.Sea)")
			}
			out.WriteString(".Flag(godip.Sea).\n")
		}
	}
	return out.String()
}

// renderSC renders the .SC() call for a supply center province.
func renderSC(m *model, key string) string {
	home, isSC := m.homeSC[key]
	if !isSC {
		return ""
	}
	if home == "" {
		return ".SC(godip.Neutral)"
	}
	return ".SC(" + goIdent(home) + ")"
}

func renderGo(j job, m *model) string {
	out := strings.Builder{}
	w := func(format string, args ...interface{}) {
		fmt.Fprintf(&out, format, args...)
	}

	w("// Code generated by tools/jdip-import. DO NOT EDIT.\n")
	w("//\n")
	w("// %v, translated from jDip's %v and %v.\n", j.displayName, j.adjacency, j.variants)
	w("//\n")
	w("// Known limitations of the translation:\n")
	for _, note := range j.notes {
		for i, line := range wrap(note, 68) {
			if i == 0 {
				w("//   - %v\n", line)
			} else {
				w("//     %v\n", line)
			}
		}
	}
	w("package %v\n\n", j.pkg)
	w("import (\n")
	w("\t_ \"embed\"\n\n")
	w("\t\"github.com/zond/godip\"\n")
	w("\t\"github.com/zond/godip/graph\"\n")
	w("\t\"github.com/zond/godip/state\"\n")
	w("\t\"github.com/zond/godip/variants/classical\"\n")
	w("\t\"github.com/zond/godip/variants/common\"\n")
	w(")\n\n")

	w("//go:embed map.svg\n")
	w("var mapSVG []byte\n\n")

	w("const (\n")
	for _, power := range m.powers {
		w("\t%v godip.Nation = %v\n", goIdent(power), quote(power))
	}
	w(")\n\n")

	w("var Nations = []godip.Nation{")
	for i, power := range m.powers {
		if i > 0 {
			w(", ")
		}
		w("%v", goIdent(power))
	}
	w("}\n\n")

	// Long names.
	w("var provinceLongNames = map[godip.Province]string{\n")
	for _, key := range m.order {
		p := m.provinces[key]
		w("\t%v: %v,\n", quote(key), quote(p.name))
		codes := []string{}
		for code := range p.coasts {
			codes = append(codes, code)
		}
		sort.Strings(codes)
		for _, code := range codes {
			w("\t%v: %v,\n", quote(key+"/"+code), quote(p.name+" ("+strings.ToUpper(code)+")"))
		}
	}
	w("}\n\n")

	w("var %vVariant = common.Variant{\n", j.ident)
	w("\tName:              %v,\n", quote(j.displayName))
	w("\tGraph:             func() godip.Graph { return %vGraph() },\n", j.ident)
	w("\tStart:             %vStart,\n", j.ident)
	w("\tBlank:             %vBlank,\n", j.ident)
	w("\tPhase:             classical.NewPhase,\n")
	w("\tParser:            classical.Parser,\n")
	w("\tNations:           Nations,\n")
	w("\tPhaseTypes:        classical.PhaseTypes,\n")
	w("\tSeasons:           classical.Seasons,\n")
	w("\tUnitTypes:         classical.UnitTypes,\n")
	w("\tSoloWinner:        common.SCCountWinner(%v),\n", m.winningSC)
	w("\tSoloSCCount:       func(*state.State) int { return %v },\n", m.winningSC)
	w("\tProvinceLongNames: provinceLongNames,\n")
	w("\tSVGMap:            func() ([]byte, error) { return mapSVG, nil },\n")
	w("\tSVGVersion:        \"1\",\n")
	w("\tSVGUnits:          classical.SVGUnits,\n")
	w("\tCreatedBy:         %v,\n", quote(j.createdBy))
	w("\tVersion:           \"1\",\n")
	w("\tDescription:       %v,\n", quote(m.description))
	w("\tRules:             %v,\n", backquote(j.rules))
	w("}\n\n")

	w("func %vBlank(phase godip.Phase) *state.State {\n", j.ident)
	w("\treturn state.New(%vGraph(), phase, classical.BackupRule, nil, nil)\n", j.ident)
	w("}\n\n")

	w("func %vStart() (result *state.State, err error) {\n", j.ident)
	w("\tstartPhase := classical.NewPhase(%v, godip.%v, godip.Movement)\n", m.year, m.season)
	w("\tresult = %vBlank(startPhase)\n", j.ident)
	w("\tif err = result.SetUnits(map[godip.Province]godip.Unit{\n")
	for _, at := range m.unitOrder {
		u := m.units[at]
		w("\t\t%v: godip.Unit{Type: godip.%v, Nation: %v},\n", quote(at), u.kind, goIdent(u.power))
	}
	w("\t}); err != nil {\n\t\treturn\n\t}\n")
	w("\tresult.SetSupplyCenters(map[godip.Province]godip.Nation{\n")
	owners := []string{}
	for prov := range m.scOwner {
		owners = append(owners, prov)
	}
	sort.Strings(owners)
	for _, prov := range owners {
		w("\t\t%v: %v,\n", quote(prov), goIdent(m.scOwner[prov]))
	}
	w("\t})\n")
	w("\treturn\n")
	w("}\n\n")

	w("func %vGraph() *graph.Graph {\n", j.ident)
	w("\treturn graph.New().\n")
	// Each province line already ends with the chaining dot, so the
	// terminating call simply follows on its own line.
	w("%v", renderGraph(m))
	w("\t\tDone()\n")
	w("}\n")

	// Formatting here keeps the checked-in output gofmt clean without a
	// second pass over the repository.
	pretty, err := format.Source([]byte(out.String()))
	if err != nil {
		log.Printf("%v: generated source does not parse (%v); writing it unformatted so the error can be read", j.key, err)
		return out.String()
	}
	return string(pretty)
}

// wrap breaks a note into comment-width lines.
func wrap(text string, width int) []string {
	words := strings.Fields(text)
	lines := []string{}
	line := ""
	for _, word := range words {
		if line == "" {
			line = word
			continue
		}
		if len(line)+1+len(word) > width {
			lines = append(lines, line)
			line = word
			continue
		}
		line += " " + word
	}
	if line != "" {
		lines = append(lines, line)
	}
	return lines
}
