// Code generated by tools/jdip-import. DO NOT EDIT.
//
// 1900, translated from jDip's 1900_adjacency.xml and variants.xml.
//
// Known limitations of the translation:
//   - The Suez half-strength and support-blocking rules are prose in
//     jDip's variant description, not data in the adjacency XML. godip has
//     no half-strength move, so they are NOT implemented: Egypt/Hejaz to
//     Mid-Atlantic moves resolve at full strength and may be supported.
//   - YEARS_WITHOUT_SC_CAPTURE (7) and GAME_LENGTH (35) draw conditions
//     are recorded here but not enforced; godip has no game-length
//     machinery.
//   - jDip's variant data carries an off-map placeholder province, dum
//     ("Dummy", alias "Russian Steamroller"), adjacent only to itself and
//     owned by Russia at start. It is kept so the supply center count
//     matches jDip, but its self-edge is dropped: no unit can enter or
//     leave it.
package jdip1900

import (
	_ "embed"

	"github.com/zond/godip"
	"github.com/zond/godip/graph"
	"github.com/zond/godip/state"
	"github.com/zond/godip/variants/classical"
	"github.com/zond/godip/variants/common"
)

//go:embed map.svg
var mapSVG []byte

const (
	Austria godip.Nation = "Austria"
	Britain godip.Nation = "Britain"
	France  godip.Nation = "France"
	Germany godip.Nation = "Germany"
	Italy   godip.Nation = "Italy"
	Russia  godip.Nation = "Russia"
	Turkey  godip.Nation = "Turkey"
)

var Nations = []godip.Nation{Austria, Britain, France, Germany, Italy, Russia, Turkey}

var provinceLongNames = map[godip.Province]string{
	"adr":    "Adriatic Sea",
	"aeg":    "Aegean Sea",
	"alg":    "Algeria",
	"als":    "Alsace",
	"ank":    "Ankara",
	"apu":    "Apulia",
	"ara":    "Arabia",
	"arm":    "Armenia",
	"bal":    "Baltic Sea",
	"bar":    "Barents Sea",
	"bel":    "Belgium",
	"ber":    "Berlin",
	"bla":    "Black Sea",
	"boh":    "Bohemia",
	"bos":    "Bosnia",
	"bre":    "Brest",
	"bud":    "Budapest",
	"bul":    "Bulgaria",
	"bur":    "Burgundy",
	"cly":    "Clyde",
	"col":    "Cologne",
	"con":    "Constantinople",
	"cyr":    "Cyrenaica",
	"dam":    "Damascus",
	"den":    "Denmark",
	"dum":    "Dummy",
	"eas":    "Eastern Mediterranean",
	"edi":    "Edinburgh",
	"egy":    "Egypt",
	"eng":    "English Channel",
	"fin":    "Finland",
	"gal":    "Galicia",
	"gas":    "Gascony",
	"gbo":    "Gulf of Bothnia",
	"gib":    "Gibraltar",
	"gly":    "Gulf of Lyon",
	"gre":    "Greece",
	"hej":    "Hejaz",
	"hel":    "Helgoland Bight",
	"ice":    "Iceland",
	"ion":    "Ionian Sea",
	"ire":    "Ireland",
	"iri":    "Irish Sea",
	"kie":    "Kiel",
	"kon":    "Konya",
	"lon":    "London",
	"lvo":    "Livonia",
	"lvp":    "Liverpool",
	"mac":    "Macedonia",
	"mac/ec": "Macedonia (EC)",
	"mac/wc": "Macedonia (WC)",
	"mar":    "Marseilles",
	"mid":    "Mid-Atlantic Ocean",
	"mil":    "Milan",
	"mor":    "Morocco",
	"mos":    "Moscow",
	"mun":    "Munich",
	"nap":    "Naples",
	"nat":    "North Atlantic Ocean",
	"net":    "Netherlands",
	"nth":    "North Sea",
	"nws":    "Norwegian Sea",
	"nwy":    "Norway",
	"pal":    "Palestine",
	"par":    "Paris",
	"pic":    "Picardy",
	"pie":    "Piedmont",
	"por":    "Portugal",
	"pru":    "Prussia",
	"rom":    "Rome",
	"rum":    "Rumania",
	"ser":    "Serbia",
	"sev":    "Sevastopol",
	"sib":    "Siberia",
	"sil":    "Silesia",
	"ska":    "Skagerrak",
	"sou":    "Southern Algeria",
	"spa":    "Spain",
	"spa/ec": "Spain (EC)",
	"spa/nc": "Spain (NC)",
	"spa/wc": "Spain (WC)",
	"stp":    "St. Petersburg",
	"stp/nc": "St. Petersburg (NC)",
	"stp/sc": "St. Petersburg (SC)",
	"swe":    "Sweden",
	"swi":    "Switzerland",
	"tri":    "Trieste",
	"trp":    "Tripolitania",
	"tun":    "Tunisia",
	"tyr":    "Tyrolia",
	"tys":    "Tyrrhenian Sea",
	"ukr":    "Ukraine",
	"ven":    "Venetia",
	"vie":    "Vienna",
	"wal":    "Wales",
	"war":    "Warsaw",
	"wes":    "Western Mediterranean",
	"yor":    "Yorkshire",
}

var Nineteen00Variant = common.Variant{
	Name:              "1900",
	Graph:             func() godip.Graph { return Nineteen00Graph() },
	Start:             Nineteen00Start,
	Blank:             Nineteen00Blank,
	Phase:             classical.NewPhase,
	Parser:            classical.Parser,
	Nations:           Nations,
	PhaseTypes:        classical.PhaseTypes,
	Seasons:           classical.Seasons,
	UnitTypes:         classical.UnitTypes,
	SoloWinner:        common.SCCountWinner(18),
	SoloSCCount:       func(*state.State) int { return 18 },
	ProvinceLongNames: provinceLongNames,
	SVGMap:            func() ([]byte, error) { return mapSVG, nil },
	SVGVersion:        "1",
	SVGUnits:          classical.SVGUnits,
	CreatedBy:         "Baron Powell and Edi Birsan",
	Version:           "1",
	Description:       "The 1900 variant of Diplomacy is an attempt to take the standard game and improve it by balancing the main powers while increasing historical accuracy and player interaction.",
	Rules: `First to 18 Supply Centers (SC) is the winner.
Builds are allowed in home centers only, so the African and Asian centers a
power starts with can never build.
Iceland, Ireland and Switzerland are passable.
Armies move between Clyde and Ireland, and between Gibraltar and Morocco,
without a convoy.
Three provinces have named coasts: Spain, Saint Petersburg and Macedonia.
Russia starts owning "Dummy", jDip's off-map center, which no unit can ever
reach or take.`,
}

func Nineteen00Blank(phase godip.Phase) *state.State {
	return state.New(Nineteen00Graph(), phase, classical.BackupRule, nil, nil)
}

func Nineteen00Start() (result *state.State, err error) {
	startPhase := classical.NewPhase(1900, godip.Spring, godip.Movement)
	result = Nineteen00Blank(startPhase)
	if err = result.SetUnits(map[godip.Province]godip.Unit{
		"alg":    godip.Unit{Type: godip.Army, Nation: France},
		"ank":    godip.Unit{Type: godip.Fleet, Nation: Turkey},
		"ber":    godip.Unit{Type: godip.Army, Nation: Germany},
		"bre":    godip.Unit{Type: godip.Fleet, Nation: France},
		"bud":    godip.Unit{Type: godip.Army, Nation: Austria},
		"col":    godip.Unit{Type: godip.Army, Nation: Germany},
		"con":    godip.Unit{Type: godip.Army, Nation: Turkey},
		"dam":    godip.Unit{Type: godip.Army, Nation: Turkey},
		"edi":    godip.Unit{Type: godip.Fleet, Nation: Britain},
		"egy":    godip.Unit{Type: godip.Fleet, Nation: Britain},
		"gib":    godip.Unit{Type: godip.Fleet, Nation: Britain},
		"kie":    godip.Unit{Type: godip.Fleet, Nation: Germany},
		"lon":    godip.Unit{Type: godip.Fleet, Nation: Britain},
		"mar":    godip.Unit{Type: godip.Army, Nation: France},
		"mil":    godip.Unit{Type: godip.Army, Nation: Italy},
		"mos":    godip.Unit{Type: godip.Army, Nation: Russia},
		"mun":    godip.Unit{Type: godip.Army, Nation: Germany},
		"nap":    godip.Unit{Type: godip.Fleet, Nation: Italy},
		"par":    godip.Unit{Type: godip.Army, Nation: France},
		"rom":    godip.Unit{Type: godip.Army, Nation: Italy},
		"sev":    godip.Unit{Type: godip.Fleet, Nation: Russia},
		"stp/sc": godip.Unit{Type: godip.Fleet, Nation: Russia},
		"tri":    godip.Unit{Type: godip.Army, Nation: Austria},
		"vie":    godip.Unit{Type: godip.Army, Nation: Austria},
		"war":    godip.Unit{Type: godip.Army, Nation: Russia},
	}); err != nil {
		return
	}
	result.SetSupplyCenters(map[godip.Province]godip.Nation{
		"alg": France,
		"ank": Turkey,
		"ber": Germany,
		"bre": France,
		"bud": Austria,
		"col": Germany,
		"con": Turkey,
		"dam": Turkey,
		"dum": Russia,
		"edi": Britain,
		"egy": Britain,
		"kie": Germany,
		"lon": Britain,
		"lvp": Britain,
		"mar": France,
		"mil": Italy,
		"mos": Russia,
		"mun": Germany,
		"nap": Italy,
		"par": France,
		"rom": Italy,
		"sev": Russia,
		"stp": Russia,
		"tri": Austria,
		"vie": Austria,
		"war": Russia,
	})
	return
}

func Nineteen00Graph() *graph.Graph {
	return graph.New().
		// Adriatic Sea
		Prov("adr").Conn("apu", godip.Sea).Conn("bos", godip.Sea).Conn("ion", godip.Sea).Conn("mac/wc", godip.Sea).Conn("tri", godip.Sea).Conn("ven", godip.Sea).Flag(godip.Sea).
		// Aegean Sea
		Prov("aeg").Conn("con", godip.Sea).Conn("eas", godip.Sea).Conn("gre", godip.Sea).Conn("ion", godip.Sea).Conn("kon", godip.Sea).Conn("mac/ec", godip.Sea).Flag(godip.Sea).
		// Algeria
		Prov("alg").Conn("mor", godip.Coast...).Conn("sou", godip.Land).Conn("tun", godip.Coast...).Conn("tys", godip.Sea).Conn("wes", godip.Sea).Flag(godip.Coast...).SC(godip.Neutral).
		// Alsace
		Prov("als").Conn("bel", godip.Land).Conn("bur", godip.Land).Conn("col", godip.Land).Conn("mun", godip.Land).Conn("swi", godip.Land).Flag(godip.Land).
		// Ankara
		Prov("ank").Conn("arm", godip.Coast...).Conn("bla", godip.Sea).Conn("con", godip.Coast...).Conn("kon", godip.Land).Flag(godip.Coast...).SC(Turkey).
		// Apulia
		Prov("apu").Conn("adr", godip.Sea).Conn("ion", godip.Sea).Conn("nap", godip.Coast...).Conn("rom", godip.Land).Conn("ven", godip.Coast...).Flag(godip.Coast...).
		// Arabia
		Prov("ara").Conn("dam", godip.Land).Conn("hej", godip.Land).Conn("pal", godip.Land).Flag(godip.Land).
		// Armenia
		Prov("arm").Conn("ank", godip.Coast...).Conn("bla", godip.Sea).Conn("dam", godip.Land).Conn("kon", godip.Land).Conn("sev", godip.Coast...).Flag(godip.Coast...).
		// Baltic Sea
		Prov("bal").Conn("ber", godip.Sea).Conn("den", godip.Sea).Conn("gbo", godip.Sea).Conn("kie", godip.Sea).Conn("lvo", godip.Sea).Conn("pru", godip.Sea).Conn("swe", godip.Sea).Flag(godip.Sea).
		// Barents Sea
		Prov("bar").Conn("nws", godip.Sea).Conn("nwy", godip.Sea).Conn("stp/nc", godip.Sea).Flag(godip.Sea).
		// Belgium
		Prov("bel").Conn("als", godip.Land).Conn("bur", godip.Land).Conn("col", godip.Land).Conn("eng", godip.Sea).Conn("net", godip.Coast...).Conn("nth", godip.Sea).Conn("pic", godip.Coast...).Flag(godip.Coast...).SC(godip.Neutral).
		// Berlin
		Prov("ber").Conn("bal", godip.Sea).Conn("kie", godip.Coast...).Conn("mun", godip.Land).Conn("pru", godip.Coast...).Conn("sil", godip.Land).Flag(godip.Coast...).SC(Germany).
		// Black Sea
		Prov("bla").Conn("ank", godip.Sea).Conn("arm", godip.Sea).Conn("bul", godip.Sea).Conn("con", godip.Sea).Conn("rum", godip.Sea).Conn("sev", godip.Sea).Flag(godip.Sea).
		// Bohemia
		Prov("boh").Conn("bud", godip.Land).Conn("gal", godip.Land).Conn("mun", godip.Land).Conn("sil", godip.Land).Conn("tyr", godip.Land).Conn("vie", godip.Land).Flag(godip.Land).
		// Bosnia
		Prov("bos").Conn("adr", godip.Sea).Conn("mac", godip.Land).Conn("mac/wc", godip.Sea).Conn("ser", godip.Land).Conn("tri", godip.Coast...).Flag(godip.Coast...).
		// Brest
		Prov("bre").Conn("eng", godip.Sea).Conn("gas", godip.Coast...).Conn("mid", godip.Sea).Conn("par", godip.Land).Conn("pic", godip.Coast...).Flag(godip.Coast...).SC(France).
		// Budapest
		Prov("bud").Conn("boh", godip.Land).Conn("gal", godip.Land).Conn("rum", godip.Land).Conn("ser", godip.Land).Conn("tri", godip.Land).Conn("vie", godip.Land).Flag(godip.Land).SC(Austria).
		// Bulgaria
		Prov("bul").Conn("bla", godip.Sea).Conn("con", godip.Coast...).Conn("mac", godip.Land).Conn("rum", godip.Coast...).Conn("ser", godip.Land).Flag(godip.Coast...).SC(godip.Neutral).
		// Burgundy
		Prov("bur").Conn("als", godip.Land).Conn("bel", godip.Land).Conn("gas", godip.Land).Conn("mar", godip.Land).Conn("par", godip.Land).Conn("pic", godip.Land).Conn("swi", godip.Land).Flag(godip.Land).
		// Clyde
		Prov("cly").Conn("edi", godip.Coast...).Conn("ire", godip.Coast...).Conn("lvp", godip.Coast...).Conn("nat", godip.Sea).Conn("nws", godip.Sea).Flag(godip.Coast...).
		// Cologne
		Prov("col").Conn("als", godip.Land).Conn("bel", godip.Land).Conn("kie", godip.Land).Conn("mun", godip.Land).Conn("net", godip.Land).Flag(godip.Land).SC(Germany).
		// Constantinople
		Prov("con").Conn("aeg", godip.Sea).Conn("ank", godip.Coast...).Conn("bla", godip.Sea).Conn("bul", godip.Coast...).Conn("kon", godip.Coast...).Conn("mac", godip.Land).Conn("mac/ec", godip.Sea).Flag(godip.Coast...).SC(Turkey).
		// Cyrenaica
		Prov("cyr").Conn("eas", godip.Sea).Conn("egy", godip.Coast...).Conn("ion", godip.Sea).Conn("trp", godip.Coast...).Flag(godip.Coast...).
		// Damascus
		Prov("dam").Conn("ara", godip.Land).Conn("arm", godip.Land).Conn("eas", godip.Sea).Conn("kon", godip.Coast...).Conn("pal", godip.Coast...).Flag(godip.Coast...).SC(Turkey).
		// Denmark
		Prov("den").Conn("bal", godip.Sea).Conn("hel", godip.Sea).Conn("kie", godip.Coast...).Conn("nth", godip.Sea).Conn("ska", godip.Sea).Conn("swe", godip.Coast...).Flag(godip.Coast...).SC(godip.Neutral).
		// Dummy
		Prov("dum").Flag(godip.Land).SC(godip.Neutral).
		// Eastern Mediterranean
		Prov("eas").Conn("aeg", godip.Sea).Conn("cyr", godip.Sea).Conn("dam", godip.Sea).Conn("egy", godip.Sea).Conn("ion", godip.Sea).Conn("kon", godip.Sea).Conn("pal", godip.Sea).Flag(godip.Sea).
		// Edinburgh
		Prov("edi").Conn("cly", godip.Coast...).Conn("lvp", godip.Land).Conn("nth", godip.Sea).Conn("nws", godip.Sea).Conn("yor", godip.Coast...).Flag(godip.Coast...).SC(Britain).
		// Egypt
		Prov("egy").Conn("cyr", godip.Coast...).Conn("eas", godip.Sea).Conn("hej", godip.Coast...).Conn("mid", godip.Sea).Conn("pal", godip.Coast...).Flag(godip.Coast...).SC(godip.Neutral).
		// English Channel
		Prov("eng").Conn("bel", godip.Sea).Conn("bre", godip.Sea).Conn("iri", godip.Sea).Conn("lon", godip.Sea).Conn("mid", godip.Sea).Conn("nth", godip.Sea).Conn("pic", godip.Sea).Conn("wal", godip.Sea).Flag(godip.Sea).
		// Finland
		Prov("fin").Conn("gbo", godip.Sea).Conn("nwy", godip.Land).Conn("stp", godip.Land).Conn("stp/sc", godip.Sea).Conn("swe", godip.Coast...).Flag(godip.Coast...).
		// Galicia
		Prov("gal").Conn("boh", godip.Land).Conn("bud", godip.Land).Conn("rum", godip.Land).Conn("sil", godip.Land).Conn("ukr", godip.Land).Conn("war", godip.Land).Flag(godip.Land).
		// Gascony
		Prov("gas").Conn("bre", godip.Coast...).Conn("bur", godip.Land).Conn("mar", godip.Land).Conn("mid", godip.Sea).Conn("par", godip.Land).Conn("spa", godip.Land).Conn("spa/nc", godip.Sea).Flag(godip.Coast...).
		// Gulf of Bothnia
		Prov("gbo").Conn("bal", godip.Sea).Conn("fin", godip.Sea).Conn("lvo", godip.Sea).Conn("stp/sc", godip.Sea).Conn("swe", godip.Sea).Flag(godip.Sea).
		// Gibraltar
		Prov("gib").Conn("mid", godip.Sea).Conn("mor", godip.Coast...).Conn("spa", godip.Land).Conn("spa/ec", godip.Sea).Conn("spa/wc", godip.Sea).Conn("wes", godip.Sea).Flag(godip.Archipelago...).
		// Gulf of Lyon
		Prov("gly").Conn("mar", godip.Sea).Conn("pie", godip.Sea).Conn("rom", godip.Sea).Conn("spa/ec", godip.Sea).Conn("tys", godip.Sea).Conn("wes", godip.Sea).Flag(godip.Sea).
		// Greece
		Prov("gre").Conn("aeg", godip.Sea).Conn("ion", godip.Sea).Conn("mac", godip.Land).Conn("mac/ec", godip.Sea).Conn("mac/wc", godip.Sea).Flag(godip.Coast...).SC(godip.Neutral).
		// Hejaz
		Prov("hej").Conn("ara", godip.Land).Conn("egy", godip.Coast...).Conn("mid", godip.Sea).Conn("pal", godip.Land).Flag(godip.Coast...).
		// Helgoland Bight
		Prov("hel").Conn("den", godip.Sea).Conn("kie", godip.Sea).Conn("net", godip.Sea).Conn("nth", godip.Sea).Flag(godip.Sea).
		// Iceland
		Prov("ice").Conn("nat", godip.Sea).Conn("nws", godip.Sea).Flag(godip.Sea).
		// Ionian Sea
		Prov("ion").Conn("adr", godip.Sea).Conn("aeg", godip.Sea).Conn("apu", godip.Sea).Conn("cyr", godip.Sea).Conn("eas", godip.Sea).Conn("gre", godip.Sea).Conn("mac/wc", godip.Sea).Conn("nap", godip.Sea).Conn("trp", godip.Sea).Conn("tun", godip.Sea).Conn("tys", godip.Sea).Flag(godip.Sea).
		// Ireland
		Prov("ire").Conn("cly", godip.Coast...).Conn("iri", godip.Sea).Conn("mid", godip.Sea).Conn("nat", godip.Sea).Flag(godip.Coast...).
		// Irish Sea
		Prov("iri").Conn("eng", godip.Sea).Conn("ire", godip.Sea).Conn("lvp", godip.Sea).Conn("mid", godip.Sea).Conn("nat", godip.Sea).Conn("wal", godip.Sea).Flag(godip.Sea).
		// Kiel
		Prov("kie").Conn("bal", godip.Sea).Conn("ber", godip.Coast...).Conn("col", godip.Land).Conn("den", godip.Coast...).Conn("hel", godip.Sea).Conn("mun", godip.Land).Conn("net", godip.Coast...).Flag(godip.Coast...).SC(Germany).
		// Konya
		Prov("kon").Conn("aeg", godip.Sea).Conn("ank", godip.Land).Conn("arm", godip.Land).Conn("con", godip.Coast...).Conn("dam", godip.Coast...).Conn("eas", godip.Sea).Flag(godip.Coast...).
		// London
		Prov("lon").Conn("eng", godip.Sea).Conn("nth", godip.Sea).Conn("wal", godip.Coast...).Conn("yor", godip.Coast...).Flag(godip.Coast...).SC(Britain).
		// Livonia
		Prov("lvo").Conn("bal", godip.Sea).Conn("gbo", godip.Sea).Conn("mos", godip.Land).Conn("pru", godip.Coast...).Conn("stp", godip.Land).Conn("stp/sc", godip.Sea).Conn("war", godip.Land).Flag(godip.Coast...).
		// Liverpool
		Prov("lvp").Conn("cly", godip.Coast...).Conn("edi", godip.Land).Conn("iri", godip.Sea).Conn("nat", godip.Sea).Conn("wal", godip.Coast...).Conn("yor", godip.Land).Flag(godip.Coast...).SC(Britain).
		// Macedonia
		Prov("mac").Conn("bos", godip.Land).Conn("bul", godip.Land).Conn("con", godip.Land).Conn("gre", godip.Land).Conn("ser", godip.Land).Flag(godip.Land).
		// Macedonia (ec)
		Prov("mac/ec").Conn("aeg", godip.Sea).Conn("con", godip.Sea).Conn("gre", godip.Sea).Flag(godip.Sea).
		// Macedonia (wc)
		Prov("mac/wc").Conn("adr", godip.Sea).Conn("bos", godip.Sea).Conn("gre", godip.Sea).Conn("ion", godip.Sea).Flag(godip.Sea).
		// Marseilles
		Prov("mar").Conn("bur", godip.Land).Conn("gas", godip.Land).Conn("gly", godip.Sea).Conn("pie", godip.Coast...).Conn("spa", godip.Land).Conn("spa/ec", godip.Sea).Conn("swi", godip.Land).Flag(godip.Coast...).SC(France).
		// Mid-Atlantic Ocean
		Prov("mid").Conn("bre", godip.Sea).Conn("egy", godip.Sea).Conn("eng", godip.Sea).Conn("gas", godip.Sea).Conn("gib", godip.Sea).Conn("hej", godip.Sea).Conn("ire", godip.Sea).Conn("iri", godip.Sea).Conn("mor", godip.Sea).Conn("nat", godip.Sea).Conn("por", godip.Sea).Conn("spa/nc", godip.Sea).Conn("spa/wc", godip.Sea).Flag(godip.Sea).
		// Milan
		Prov("mil").Conn("pie", godip.Land).Conn("rom", godip.Land).Conn("swi", godip.Land).Conn("tyr", godip.Land).Conn("ven", godip.Land).Flag(godip.Land).SC(Italy).
		// Morocco
		Prov("mor").Conn("alg", godip.Coast...).Conn("gib", godip.Coast...).Conn("mid", godip.Sea).Conn("sou", godip.Land).Conn("wes", godip.Sea).Flag(godip.Coast...).SC(godip.Neutral).
		// Moscow
		Prov("mos").Conn("lvo", godip.Land).Conn("sev", godip.Land).Conn("sib", godip.Land).Conn("stp", godip.Land).Conn("ukr", godip.Land).Conn("war", godip.Land).Flag(godip.Land).SC(Russia).
		// Munich
		Prov("mun").Conn("als", godip.Land).Conn("ber", godip.Land).Conn("boh", godip.Land).Conn("col", godip.Land).Conn("kie", godip.Land).Conn("sil", godip.Land).Conn("swi", godip.Land).Conn("tyr", godip.Land).Flag(godip.Land).SC(Germany).
		// Naples
		Prov("nap").Conn("apu", godip.Coast...).Conn("ion", godip.Sea).Conn("rom", godip.Coast...).Conn("tys", godip.Sea).Flag(godip.Coast...).SC(Italy).
		// North Atlantic Ocean
		Prov("nat").Conn("cly", godip.Sea).Conn("ice", godip.Sea).Conn("ire", godip.Sea).Conn("iri", godip.Sea).Conn("lvp", godip.Sea).Conn("mid", godip.Sea).Conn("nws", godip.Sea).Flag(godip.Sea).
		// Netherlands
		Prov("net").Conn("bel", godip.Coast...).Conn("col", godip.Land).Conn("hel", godip.Sea).Conn("kie", godip.Coast...).Conn("nth", godip.Sea).Flag(godip.Coast...).SC(godip.Neutral).
		// North Sea
		Prov("nth").Conn("bel", godip.Sea).Conn("den", godip.Sea).Conn("edi", godip.Sea).Conn("eng", godip.Sea).Conn("hel", godip.Sea).Conn("lon", godip.Sea).Conn("net", godip.Sea).Conn("nws", godip.Sea).Conn("nwy", godip.Sea).Conn("ska", godip.Sea).Conn("yor", godip.Sea).Flag(godip.Sea).
		// Norwegian Sea
		Prov("nws").Conn("bar", godip.Sea).Conn("cly", godip.Sea).Conn("edi", godip.Sea).Conn("ice", godip.Sea).Conn("nat", godip.Sea).Conn("nth", godip.Sea).Conn("nwy", godip.Sea).Flag(godip.Sea).
		// Norway
		Prov("nwy").Conn("bar", godip.Sea).Conn("fin", godip.Land).Conn("nth", godip.Sea).Conn("nws", godip.Sea).Conn("ska", godip.Sea).Conn("stp", godip.Land).Conn("stp/nc", godip.Sea).Conn("swe", godip.Coast...).Flag(godip.Coast...).SC(godip.Neutral).
		// Palestine
		Prov("pal").Conn("ara", godip.Land).Conn("dam", godip.Coast...).Conn("eas", godip.Sea).Conn("egy", godip.Coast...).Conn("hej", godip.Land).Flag(godip.Coast...).
		// Paris
		Prov("par").Conn("bre", godip.Land).Conn("bur", godip.Land).Conn("gas", godip.Land).Conn("pic", godip.Land).Flag(godip.Land).SC(France).
		// Picardy
		Prov("pic").Conn("bel", godip.Coast...).Conn("bre", godip.Coast...).Conn("bur", godip.Land).Conn("eng", godip.Sea).Conn("par", godip.Land).Flag(godip.Coast...).
		// Piedmont
		Prov("pie").Conn("gly", godip.Sea).Conn("mar", godip.Coast...).Conn("mil", godip.Land).Conn("rom", godip.Coast...).Conn("swi", godip.Land).Flag(godip.Coast...).
		// Portugal
		Prov("por").Conn("mid", godip.Sea).Conn("spa", godip.Land).Conn("spa/nc", godip.Sea).Conn("spa/wc", godip.Sea).Flag(godip.Coast...).SC(godip.Neutral).
		// Prussia
		Prov("pru").Conn("bal", godip.Sea).Conn("ber", godip.Coast...).Conn("lvo", godip.Coast...).Conn("sil", godip.Land).Conn("war", godip.Land).Flag(godip.Coast...).
		// Rome
		Prov("rom").Conn("apu", godip.Land).Conn("gly", godip.Sea).Conn("mil", godip.Land).Conn("nap", godip.Coast...).Conn("pie", godip.Coast...).Conn("tys", godip.Sea).Conn("ven", godip.Land).Flag(godip.Coast...).SC(Italy).
		// Rumania
		Prov("rum").Conn("bla", godip.Sea).Conn("bud", godip.Land).Conn("bul", godip.Coast...).Conn("gal", godip.Land).Conn("ser", godip.Land).Conn("sev", godip.Coast...).Conn("ukr", godip.Land).Flag(godip.Coast...).SC(godip.Neutral).
		// Serbia
		Prov("ser").Conn("bos", godip.Land).Conn("bud", godip.Land).Conn("bul", godip.Land).Conn("mac", godip.Land).Conn("rum", godip.Land).Conn("tri", godip.Land).Flag(godip.Land).SC(godip.Neutral).
		// Sevastopol
		Prov("sev").Conn("arm", godip.Coast...).Conn("bla", godip.Sea).Conn("mos", godip.Land).Conn("rum", godip.Coast...).Conn("sib", godip.Land).Conn("ukr", godip.Land).Flag(godip.Coast...).SC(Russia).
		// Siberia
		Prov("sib").Conn("mos", godip.Land).Conn("sev", godip.Land).Conn("stp", godip.Land).Flag(godip.Land).
		// Silesia
		Prov("sil").Conn("ber", godip.Land).Conn("boh", godip.Land).Conn("gal", godip.Land).Conn("mun", godip.Land).Conn("pru", godip.Land).Conn("war", godip.Land).Flag(godip.Land).
		// Skagerrak
		Prov("ska").Conn("den", godip.Sea).Conn("nth", godip.Sea).Conn("nwy", godip.Sea).Conn("swe", godip.Sea).Flag(godip.Sea).
		// Southern Algeria
		Prov("sou").Conn("alg", godip.Land).Conn("mor", godip.Land).Conn("trp", godip.Land).Conn("tun", godip.Land).Flag(godip.Land).
		// Spain
		Prov("spa").Conn("gas", godip.Land).Conn("gib", godip.Land).Conn("mar", godip.Land).Conn("por", godip.Land).Flag(godip.Land).SC(godip.Neutral).
		// Spain (ec)
		Prov("spa/ec").Conn("gib", godip.Sea).Conn("gly", godip.Sea).Conn("mar", godip.Sea).Conn("wes", godip.Sea).Flag(godip.Sea).
		// Spain (nc)
		Prov("spa/nc").Conn("gas", godip.Sea).Conn("mid", godip.Sea).Conn("por", godip.Sea).Flag(godip.Sea).
		// Spain (wc)
		Prov("spa/wc").Conn("gib", godip.Sea).Conn("mid", godip.Sea).Conn("por", godip.Sea).Flag(godip.Sea).
		// St. Petersburg
		Prov("stp").Conn("fin", godip.Land).Conn("lvo", godip.Land).Conn("mos", godip.Land).Conn("nwy", godip.Land).Conn("sib", godip.Land).Flag(godip.Land).SC(Russia).
		// St. Petersburg (nc)
		Prov("stp/nc").Conn("bar", godip.Sea).Conn("nwy", godip.Sea).Flag(godip.Sea).
		// St. Petersburg (sc)
		Prov("stp/sc").Conn("fin", godip.Sea).Conn("gbo", godip.Sea).Conn("lvo", godip.Sea).Flag(godip.Sea).
		// Sweden
		Prov("swe").Conn("bal", godip.Sea).Conn("den", godip.Coast...).Conn("fin", godip.Coast...).Conn("gbo", godip.Sea).Conn("nwy", godip.Coast...).Conn("ska", godip.Sea).Flag(godip.Coast...).SC(godip.Neutral).
		// Switzerland
		Prov("swi").Conn("als", godip.Land).Conn("bur", godip.Land).Conn("mar", godip.Land).Conn("mil", godip.Land).Conn("mun", godip.Land).Conn("pie", godip.Land).Conn("tyr", godip.Land).Flag(godip.Land).SC(godip.Neutral).
		// Trieste
		Prov("tri").Conn("adr", godip.Sea).Conn("bos", godip.Coast...).Conn("bud", godip.Land).Conn("ser", godip.Land).Conn("tyr", godip.Land).Conn("ven", godip.Coast...).Conn("vie", godip.Land).Flag(godip.Coast...).SC(Austria).
		// Tripolitania
		Prov("trp").Conn("cyr", godip.Coast...).Conn("ion", godip.Sea).Conn("sou", godip.Land).Conn("tun", godip.Coast...).Flag(godip.Coast...).SC(godip.Neutral).
		// Tunisia
		Prov("tun").Conn("alg", godip.Coast...).Conn("ion", godip.Sea).Conn("sou", godip.Land).Conn("trp", godip.Coast...).Conn("tys", godip.Sea).Flag(godip.Coast...).
		// Tyrolia
		Prov("tyr").Conn("boh", godip.Land).Conn("mil", godip.Land).Conn("mun", godip.Land).Conn("swi", godip.Land).Conn("tri", godip.Land).Conn("ven", godip.Land).Conn("vie", godip.Land).Flag(godip.Land).
		// Tyrrhenian Sea
		Prov("tys").Conn("alg", godip.Sea).Conn("gly", godip.Sea).Conn("ion", godip.Sea).Conn("nap", godip.Sea).Conn("rom", godip.Sea).Conn("tun", godip.Sea).Conn("wes", godip.Sea).Flag(godip.Sea).
		// Ukraine
		Prov("ukr").Conn("gal", godip.Land).Conn("mos", godip.Land).Conn("rum", godip.Land).Conn("sev", godip.Land).Conn("war", godip.Land).Flag(godip.Land).
		// Venetia
		Prov("ven").Conn("adr", godip.Sea).Conn("apu", godip.Coast...).Conn("mil", godip.Land).Conn("rom", godip.Land).Conn("tri", godip.Coast...).Conn("tyr", godip.Land).Flag(godip.Coast...).
		// Vienna
		Prov("vie").Conn("boh", godip.Land).Conn("bud", godip.Land).Conn("tri", godip.Land).Conn("tyr", godip.Land).Flag(godip.Land).SC(Austria).
		// Wales
		Prov("wal").Conn("eng", godip.Sea).Conn("iri", godip.Sea).Conn("lon", godip.Coast...).Conn("lvp", godip.Coast...).Conn("yor", godip.Land).Flag(godip.Coast...).
		// Warsaw
		Prov("war").Conn("gal", godip.Land).Conn("lvo", godip.Land).Conn("mos", godip.Land).Conn("pru", godip.Land).Conn("sil", godip.Land).Conn("ukr", godip.Land).Flag(godip.Land).SC(Russia).
		// Western Mediterranean
		Prov("wes").Conn("alg", godip.Sea).Conn("gib", godip.Sea).Conn("gly", godip.Sea).Conn("mor", godip.Sea).Conn("spa/ec", godip.Sea).Conn("tys", godip.Sea).Flag(godip.Sea).
		// Yorkshire
		Prov("yor").Conn("edi", godip.Coast...).Conn("lon", godip.Coast...).Conn("lvp", godip.Land).Conn("nth", godip.Sea).Conn("wal", godip.Land).Flag(godip.Coast...).
		Done()
}
