// Code generated by tools/jdip-import. DO NOT EDIT.
//
// Sail Ho!, translated from jDip's sailho_adjacency.xml and variants.xml.
//
// Known limitations of the translation:
//   - Sail Ho! declares no RULEOPTIONS, so standard Diplomacy rules apply
//     throughout and nothing needed hand work.
package sailho

import (
	_ "embed"

	"github.com/zond/godip"
	"github.com/zond/godip/graph"
	"github.com/zond/godip/state"
	"github.com/zond/godip/variants/classical"
	"github.com/zond/godip/variants/common"
)

//go:embed map.svg
var mapSVG []byte

const (
	North godip.Nation = "North"
	South godip.Nation = "South"
	West  godip.Nation = "West"
	East  godip.Nation = "East"
)

var Nations = []godip.Nation{North, South, West, East}

var provinceLongNames = map[godip.Province]string{
	"aeo":    "Village of Aeolus",
	"alc":    "Alcmene's Village",
	"ama":    "Amazon Village",
	"aph":    "Aphrodite's Beach",
	"are":    "Palace of Ares",
	"arg":    "Argo's Pasture",
	"aut":    "Autolycus' Hideout",
	"cal":    "Callisto's Stronghold",
	"cec":    "Cecrops' Channel",
	"cen":    "Centaur Forest",
	"cha":    "Charon's Crossing",
	"chi":    "Chiron's Cave",
	"cup":    "Cupid's Cloud",
	"dei":    "Deianeira's Grave",
	"eas":    "Eastern Ocean",
	"ech":    "Echo's Glade",
	"ely":    "Elysian Fields",
	"fie":    "Field of the Golden Fleece",
	"fir":    "Sea of Fire",
	"fur":    "Realm of the 3 Furies",
	"gab":    "Gabrielle's Village",
	"gli":    "Glittering Gulf",
	"goc":    "Gulf of Chains",
	"had":    "Depths of Hades",
	"her":    "Hercules' Respite",
	"hes":    "Shrine to Hestia",
	"hes/nc": "Shrine to Hestia (NC)",
	"hes/sc": "Shrine to Hestia (SC)",
	"hin":    "Forest of the Golden Hind",
	"hip":    "Hippolyta's Girdle",
	"jas":    "Jason's Kingdom",
	"jox":    "Joxter's Retreat",
	"lbs":    "Lesbian Sea",
	"les":    "Isle of Lesbos",
	"lov":    "Lover's Lane",
	"mid":    "Realm of King Midas",
	"min":    "Minotaur's Labyrinth",
	"mor":    "Morpheus' Palace",
	"nar":    "Narcissus' Reflection",
	"nes":    "Nestor's Kingdom",
	"oly":    "Mount Olympus",
	"pea":    "Ocean of Peace",
	"per":    "Persephone's Garden",
	"pos":    "Poseidon's Curse",
	"pro":    "Prometheus' Cliff",
	"psy":    "Village of Psyche",
	"psy/ec": "Village of Psyche (EC)",
	"psy/wc": "Village of Psyche (WC)",
	"sal":    "Salmonius' Scheme",
	"sch":    "Scholars Channel",
	"ser":    "Serina's Village",
	"sis":    "Sisyphus' Hill",
	"soa":    "Sea of Arrows",
	"sod":    "Sea of Dreams",
	"sot":    "Sea of Tears",
	"sou":    "South Sea",
	"sow":    "Sea of Waves",
	"str":    "Strife's Cave",
	"tan":    "Tantalus' Pool",
	"tar":    "Tartarus",
	"ves":    "Convent of the Vestal Virgins",
	"wes":    "Western Ocean",
	"xen":    "Xena's Rest",
	"zeu":    "Temple of Zeus",
}

var SailHoVariant = common.Variant{
	Name:              "Sail Ho!",
	Graph:             func() godip.Graph { return SailHoGraph() },
	Start:             SailHoStart,
	Blank:             SailHoBlank,
	Phase:             classical.NewPhase,
	Parser:            classical.Parser,
	Nations:           Nations,
	PhaseTypes:        classical.PhaseTypes,
	Seasons:           classical.Seasons,
	UnitTypes:         classical.UnitTypes,
	SoloWinner:        common.SCCountWinner(9),
	SoloSCCount:       func(*state.State) int { return 9 },
	ProvinceLongNames: provinceLongNames,
	SVGMap:            func() ([]byte, error) { return mapSVG, nil },
	SVGVersion:        "1",
	SVGUnits:          classical.SVGUnits,
	CreatedBy:         "Tarzan",
	Version:           "1",
	Description:       "There are 4 powers in the Sail Ho! variant. Each power has 2 Home Supply Centers (SCs). The Map contains a total of 16 SCs; half of these SCs are Home SCs and half are \"neutral\" SCs. Victory is achieved when 9 SCs are controlled by a single power.",
	Rules: `First to 9 of the 16 Supply Centers (SC) is the winner.
Four powers, two home centers each; the other eight centers are neutral.
Half the centers sit on islands, so convoys decide the game.
Two provinces have named coasts: Hesperides and Psyche's Isle.`,
}

func SailHoBlank(phase godip.Phase) *state.State {
	return state.New(SailHoGraph(), phase, classical.BackupRule, nil, nil)
}

func SailHoStart() (result *state.State, err error) {
	startPhase := classical.NewPhase(1901, godip.Spring, godip.Movement)
	result = SailHoBlank(startPhase)
	if err = result.SetUnits(map[godip.Province]godip.Unit{
		"aeo": godip.Unit{Type: godip.Army, Nation: North},
		"ama": godip.Unit{Type: godip.Fleet, Nation: East},
		"cen": godip.Unit{Type: godip.Army, Nation: East},
		"had": godip.Unit{Type: godip.Army, Nation: South},
		"her": godip.Unit{Type: godip.Army, Nation: North},
		"les": godip.Unit{Type: godip.Fleet, Nation: West},
		"ves": godip.Unit{Type: godip.Fleet, Nation: West},
		"xen": godip.Unit{Type: godip.Fleet, Nation: South},
	}); err != nil {
		return
	}
	result.SetSupplyCenters(map[godip.Province]godip.Nation{
		"aeo": North,
		"ama": East,
		"cen": East,
		"had": South,
		"her": North,
		"les": West,
		"ves": West,
		"xen": South,
	})
	return
}

func SailHoGraph() *graph.Graph {
	return graph.New().
		// Village of Aeolus
		Prov("aeo").Conn("chi", godip.Coast...).Conn("gli", godip.Sea).Conn("mid", godip.Coast...).Conn("nar", godip.Sea).Conn("oly", godip.Land).Conn("tan", godip.Land).Conn("zeu", godip.Land).Flag(godip.Coast...).SC(North).
		// Alcmene's Village
		Prov("alc").Conn("fie", godip.Land).Conn("goc", godip.Sea).Conn("her", godip.Coast...).Conn("jas", godip.Land).Conn("mor", godip.Coast...).Conn("sod", godip.Sea).Flag(godip.Coast...).
		// Amazon Village
		Prov("ama").Conn("eas", godip.Sea).Conn("ech", godip.Coast...).Conn("hip", godip.Coast...).Conn("sch", godip.Sea).Conn("sow", godip.Sea).Flag(godip.Coast...).SC(East).
		// Aphrodite's Beach
		Prov("aph").Conn("psy", godip.Land).Conn("psy/ec", godip.Sea).Conn("psy/wc", godip.Sea).Conn("sch", godip.Sea).Conn("soa", godip.Sea).Conn("sow", godip.Sea).Flag(godip.Coast...).SC(godip.Neutral).
		// Palace of Ares
		Prov("are").Conn("hin", godip.Land).Conn("nes", godip.Land).Conn("ser", godip.Land).Conn("str", godip.Land).Flag(godip.Land).SC(godip.Neutral).
		// Argo's Pasture
		Prov("arg").Conn("cec", godip.Sea).Conn("jox", godip.Coast...).Conn("sou", godip.Sea).Conn("xen", godip.Coast...).Flag(godip.Coast...).
		// Autolycus' Hideout
		Prov("aut").Conn("cal", godip.Land).Conn("gab", godip.Land).Conn("jox", godip.Land).Conn("xen", godip.Land).Flag(godip.Land).
		// Callisto's Stronghold
		Prov("cal").Conn("aut", godip.Land).Conn("fur", godip.Land).Conn("gab", godip.Land).Conn("had", godip.Land).Conn("per", godip.Land).Flag(godip.Land).
		// Cecrops' Channel
		Prov("cec").Conn("arg", godip.Sea).Conn("eas", godip.Sea).Conn("hin", godip.Sea).Conn("pos", godip.Sea).Conn("sou", godip.Sea).Conn("str", godip.Sea).Conn("xen", godip.Sea).Flag(godip.Sea).
		// Centaur Forest
		Prov("cen").Conn("chi", godip.Coast...).Conn("ech", godip.Coast...).Conn("min", godip.Land).Conn("nar", godip.Sea).Conn("sis", godip.Land).Flag(godip.Coast...).SC(East).
		// Charon's Crossing
		Prov("cha").Conn("ely", godip.Coast...).Conn("pea", godip.Sea).Conn("tar", godip.Coast...).Flag(godip.Coast...).
		// Chiron's Cave
		Prov("chi").Conn("aeo", godip.Coast...).Conn("cen", godip.Coast...).Conn("nar", godip.Sea).Conn("sis", godip.Land).Conn("tan", godip.Land).Flag(godip.Coast...).
		// Cupid's Cloud
		Prov("cup").Conn("lov", godip.Sea).Conn("psy", godip.Land).Conn("psy/ec", godip.Sea).Conn("psy/wc", godip.Sea).Conn("sch", godip.Sea).Conn("soa", godip.Sea).Flag(godip.Coast...).SC(godip.Neutral).
		// Deianeira's Grave
		Prov("dei").Conn("fie", godip.Land).Conn("her", godip.Land).Conn("oly", godip.Land).Conn("zeu", godip.Land).Flag(godip.Land).
		// Eastern Ocean
		Prov("eas").Conn("ama", godip.Sea).Conn("cec", godip.Sea).Conn("hip", godip.Sea).Conn("min", godip.Sea).Conn("sch", godip.Sea).Conn("ser", godip.Sea).Conn("sou", godip.Sea).Conn("str", godip.Sea).Flag(godip.Sea).
		// Echo's Glade
		Prov("ech").Conn("ama", godip.Coast...).Conn("cen", godip.Coast...).Conn("hip", godip.Land).Conn("min", godip.Land).Conn("nar", godip.Sea).Conn("sow", godip.Sea).Flag(godip.Coast...).
		// Elysian Fields
		Prov("ely").Conn("cha", godip.Coast...).Conn("fur", godip.Land).Conn("pea", godip.Sea).Conn("tar", godip.Land).Flag(godip.Coast...).
		// Field of the Golden Fleece
		Prov("fie").Conn("alc", godip.Land).Conn("dei", godip.Land).Conn("her", godip.Land).Conn("jas", godip.Land).Flag(godip.Land).
		// Sea of Fire
		Prov("fir").Conn("hes/sc", godip.Sea).Conn("lbs", godip.Sea).Conn("les", godip.Sea).Conn("lov", godip.Sea).Conn("pea", godip.Sea).Conn("per", godip.Sea).Conn("sot", godip.Sea).Conn("tar", godip.Sea).Conn("ves", godip.Sea).Flag(godip.Sea).
		// Realm of the 3 Furies
		Prov("fur").Conn("cal", godip.Land).Conn("ely", godip.Land).Conn("per", godip.Land).Conn("tar", godip.Land).Flag(godip.Land).
		// Gabrielle's Village
		Prov("gab").Conn("aut", godip.Land).Conn("cal", godip.Land).Conn("had", godip.Coast...).Conn("pos", godip.Sea).Conn("sot", godip.Sea).Conn("xen", godip.Coast...).Flag(godip.Coast...).
		// Glittering Gulf
		Prov("gli").Conn("aeo", godip.Sea).Conn("mid", godip.Sea).Conn("nar", godip.Sea).Conn("pro", godip.Sea).Conn("sow", godip.Sea).Flag(godip.Sea).
		// Gulf of Chains
		Prov("goc").Conn("alc", godip.Sea).Conn("her", godip.Sea).Conn("pro", godip.Sea).Conn("sal", godip.Sea).Conn("soa", godip.Sea).Conn("sod", godip.Sea).Flag(godip.Sea).
		// Depths of Hades
		Prov("had").Conn("cal", godip.Land).Conn("gab", godip.Coast...).Conn("per", godip.Coast...).Conn("sot", godip.Sea).Flag(godip.Coast...).SC(South).
		// Hercules' Respite
		Prov("her").Conn("alc", godip.Coast...).Conn("dei", godip.Land).Conn("fie", godip.Land).Conn("goc", godip.Sea).Conn("oly", godip.Land).Conn("sal", godip.Coast...).Flag(godip.Coast...).SC(North).
		// Shrine to Hestia
		Prov("hes").Conn("les", godip.Land).Conn("ves", godip.Land).Flag(godip.Land).
		// Shrine to Hestia (nc)
		Prov("hes/nc").Conn("les", godip.Sea).Conn("soa", godip.Sea).Conn("ves", godip.Sea).Flag(godip.Sea).
		// Shrine to Hestia (sc)
		Prov("hes/sc").Conn("fir", godip.Sea).Conn("les", godip.Sea).Conn("ves", godip.Sea).Flag(godip.Sea).
		// Forest of the Golden Hind
		Prov("hin").Conn("are", godip.Land).Conn("cec", godip.Sea).Conn("nes", godip.Coast...).Conn("pos", godip.Sea).Conn("str", godip.Coast...).Flag(godip.Coast...).
		// Hippolyta's Girdle
		Prov("hip").Conn("ama", godip.Coast...).Conn("eas", godip.Sea).Conn("ech", godip.Land).Conn("min", godip.Coast...).Flag(godip.Coast...).
		// Jason's Kingdom
		Prov("jas").Conn("alc", godip.Land).Conn("fie", godip.Land).Conn("mor", godip.Coast...).Conn("wes", godip.Sea).Flag(godip.Coast...).
		// Joxter's Retreat
		Prov("jox").Conn("arg", godip.Coast...).Conn("aut", godip.Land).Conn("sou", godip.Sea).Conn("xen", godip.Land).Flag(godip.Coast...).
		// Lesbian Sea
		Prov("lbs").Conn("fir", godip.Sea).Conn("les", godip.Sea).Conn("pea", godip.Sea).Conn("wes", godip.Sea).Flag(godip.Sea).
		// Isle of Lesbos
		Prov("les").Conn("fir", godip.Sea).Conn("hes", godip.Land).Conn("hes/nc", godip.Sea).Conn("hes/sc", godip.Sea).Conn("lbs", godip.Sea).Conn("soa", godip.Sea).Conn("wes", godip.Sea).Flag(godip.Coast...).SC(West).
		// Lover's Lane
		Prov("lov").Conn("cup", godip.Sea).Conn("fir", godip.Sea).Conn("nes", godip.Sea).Conn("pos", godip.Sea).Conn("sch", godip.Sea).Conn("soa", godip.Sea).Conn("sot", godip.Sea).Conn("ves", godip.Sea).Flag(godip.Sea).
		// Realm of King Midas
		Prov("mid").Conn("aeo", godip.Coast...).Conn("gli", godip.Sea).Conn("oly", godip.Land).Conn("pro", godip.Coast...).Conn("sal", godip.Land).Flag(godip.Coast...).
		// Minotaur's Labyrinth
		Prov("min").Conn("cen", godip.Land).Conn("eas", godip.Sea).Conn("ech", godip.Land).Conn("hip", godip.Coast...).Conn("sis", godip.Land).Flag(godip.Coast...).
		// Morpheus' Palace
		Prov("mor").Conn("alc", godip.Coast...).Conn("jas", godip.Coast...).Conn("sod", godip.Sea).Conn("wes", godip.Sea).Flag(godip.Coast...).SC(godip.Neutral).
		// Narcissus' Reflection
		Prov("nar").Conn("aeo", godip.Sea).Conn("cen", godip.Sea).Conn("chi", godip.Sea).Conn("ech", godip.Sea).Conn("gli", godip.Sea).Conn("sow", godip.Sea).Flag(godip.Sea).
		// Nestor's Kingdom
		Prov("nes").Conn("are", godip.Land).Conn("hin", godip.Coast...).Conn("lov", godip.Sea).Conn("pos", godip.Sea).Conn("sch", godip.Sea).Conn("ser", godip.Coast...).Flag(godip.Coast...).SC(godip.Neutral).
		// Mount Olympus
		Prov("oly").Conn("aeo", godip.Land).Conn("dei", godip.Land).Conn("her", godip.Land).Conn("mid", godip.Land).Conn("sal", godip.Land).Conn("zeu", godip.Land).Flag(godip.Land).
		// Ocean of Peace
		Prov("pea").Conn("cha", godip.Sea).Conn("ely", godip.Sea).Conn("fir", godip.Sea).Conn("lbs", godip.Sea).Conn("tar", godip.Sea).Flag(godip.Sea).
		// Persephone's Garden
		Prov("per").Conn("cal", godip.Land).Conn("fir", godip.Sea).Conn("fur", godip.Land).Conn("had", godip.Coast...).Conn("sot", godip.Sea).Conn("tar", godip.Coast...).Flag(godip.Coast...).
		// Poseidon's Curse
		Prov("pos").Conn("cec", godip.Sea).Conn("gab", godip.Sea).Conn("hin", godip.Sea).Conn("lov", godip.Sea).Conn("nes", godip.Sea).Conn("sot", godip.Sea).Conn("xen", godip.Sea).Flag(godip.Sea).
		// Prometheus' Cliff
		Prov("pro").Conn("gli", godip.Sea).Conn("goc", godip.Sea).Conn("mid", godip.Coast...).Conn("sal", godip.Coast...).Conn("soa", godip.Sea).Conn("sow", godip.Sea).Flag(godip.Coast...).SC(godip.Neutral).
		// Village of Psyche
		Prov("psy").Conn("aph", godip.Land).Conn("cup", godip.Land).Flag(godip.Land).
		// Village of Psyche (ec)
		Prov("psy/ec").Conn("aph", godip.Sea).Conn("cup", godip.Sea).Conn("sch", godip.Sea).Flag(godip.Sea).
		// Village of Psyche (wc)
		Prov("psy/wc").Conn("aph", godip.Sea).Conn("cup", godip.Sea).Conn("soa", godip.Sea).Flag(godip.Sea).
		// Salmonius' Scheme
		Prov("sal").Conn("goc", godip.Sea).Conn("her", godip.Coast...).Conn("mid", godip.Land).Conn("oly", godip.Land).Conn("pro", godip.Coast...).Flag(godip.Coast...).
		// Scholars Channel
		Prov("sch").Conn("ama", godip.Sea).Conn("aph", godip.Sea).Conn("cup", godip.Sea).Conn("eas", godip.Sea).Conn("lov", godip.Sea).Conn("nes", godip.Sea).Conn("psy/ec", godip.Sea).Conn("ser", godip.Sea).Conn("sow", godip.Sea).Flag(godip.Sea).
		// Serina's Village
		Prov("ser").Conn("are", godip.Land).Conn("eas", godip.Sea).Conn("nes", godip.Coast...).Conn("sch", godip.Sea).Conn("str", godip.Coast...).Flag(godip.Coast...).
		// Sisyphus' Hill
		Prov("sis").Conn("cen", godip.Land).Conn("chi", godip.Land).Conn("min", godip.Land).Conn("tan", godip.Land).Flag(godip.Land).
		// Sea of Arrows
		Prov("soa").Conn("aph", godip.Sea).Conn("cup", godip.Sea).Conn("goc", godip.Sea).Conn("hes/nc", godip.Sea).Conn("les", godip.Sea).Conn("lov", godip.Sea).Conn("pro", godip.Sea).Conn("psy/wc", godip.Sea).Conn("sod", godip.Sea).Conn("sow", godip.Sea).Conn("ves", godip.Sea).Conn("wes", godip.Sea).Flag(godip.Sea).
		// Sea of Dreams
		Prov("sod").Conn("alc", godip.Sea).Conn("goc", godip.Sea).Conn("mor", godip.Sea).Conn("soa", godip.Sea).Conn("wes", godip.Sea).Flag(godip.Sea).
		// Sea of Tears
		Prov("sot").Conn("fir", godip.Sea).Conn("gab", godip.Sea).Conn("had", godip.Sea).Conn("lov", godip.Sea).Conn("per", godip.Sea).Conn("pos", godip.Sea).Flag(godip.Sea).
		// South Sea
		Prov("sou").Conn("arg", godip.Sea).Conn("cec", godip.Sea).Conn("eas", godip.Sea).Conn("jox", godip.Sea).Flag(godip.Sea).
		// Sea of Waves
		Prov("sow").Conn("ama", godip.Sea).Conn("aph", godip.Sea).Conn("ech", godip.Sea).Conn("gli", godip.Sea).Conn("nar", godip.Sea).Conn("pro", godip.Sea).Conn("sch", godip.Sea).Conn("soa", godip.Sea).Flag(godip.Sea).
		// Strife's Cave
		Prov("str").Conn("are", godip.Land).Conn("cec", godip.Sea).Conn("eas", godip.Sea).Conn("hin", godip.Coast...).Conn("ser", godip.Coast...).Flag(godip.Coast...).SC(godip.Neutral).
		// Tantalus' Pool
		Prov("tan").Conn("aeo", godip.Land).Conn("chi", godip.Land).Conn("sis", godip.Land).Conn("zeu", godip.Land).Flag(godip.Land).
		// Tartarus
		Prov("tar").Conn("cha", godip.Coast...).Conn("ely", godip.Land).Conn("fir", godip.Sea).Conn("fur", godip.Land).Conn("pea", godip.Sea).Conn("per", godip.Coast...).Flag(godip.Coast...).SC(godip.Neutral).
		// Convent of the Vestal Virgins
		Prov("ves").Conn("fir", godip.Sea).Conn("hes", godip.Land).Conn("hes/nc", godip.Sea).Conn("hes/sc", godip.Sea).Conn("lov", godip.Sea).Conn("soa", godip.Sea).Flag(godip.Coast...).SC(West).
		// Western Ocean
		Prov("wes").Conn("jas", godip.Sea).Conn("lbs", godip.Sea).Conn("les", godip.Sea).Conn("mor", godip.Sea).Conn("soa", godip.Sea).Conn("sod", godip.Sea).Flag(godip.Sea).
		// Xena's Rest
		Prov("xen").Conn("arg", godip.Coast...).Conn("aut", godip.Land).Conn("cec", godip.Sea).Conn("gab", godip.Coast...).Conn("jox", godip.Land).Conn("pos", godip.Sea).Flag(godip.Coast...).SC(South).
		// Temple of Zeus
		Prov("zeu").Conn("aeo", godip.Land).Conn("dei", godip.Land).Conn("oly", godip.Land).Conn("tan", godip.Land).Flag(godip.Land).
		Done()
}
